### ISSUE TITLE
Error grabbing logs: EOF

### ISSUE THREAD

**Issue by MBalazs90** [RemotePixel/amazonlinux-gdal#1]
I tried deploying your image but I always got this error:

`Error grabbing logs: EOF`

**Comment by vincentsarago** [comment]
👋 Salut ! 

I'm not sure to understand what you're trying to do. can you give more context and you Docker version @MBalazs90 ?

**Comment by MBalazs90** [comment]
I pulled your image from dockerhub, it always exits with the following error: `Error grabbing logs: EOF`

Im using Alpine Linux  3.7.0
```
localhost:~# docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.2
 Git commit:   b22a36dc8a
 Built:        Tue Nov 21 07:44:20 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   v17.10.0-ce
 Built:        Tue Nov 21 07:43:42 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
I tried on Ubuntu 16.04 too with:

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by vincentsarago** [comment]
well I'm not sure what's happening, can you show the full log of what you are doing ? 
FYI I'm not a docker expert

**Comment by MBalazs90** [comment]
I pulled your image from dockerhub and it always stops right away after deploying the container. Then I checked the logs and it says this error message: `Error grabbing logs: EOF`

**Comment by vincentsarago** [comment]
I'm sorry I don't see what's going on! 
you can maybe try to build the image yourself

```
git clone https://github.com/RemotePixel/amazonlinux-gdal.git
cd amazonlinux-gdal
docker build --tag remotepixel-gdal:latest .
```

**Comment by MBalazs90** [comment]
thank you. it works. I dont know what was the problem with the prebuild image?!
