### ISSUE TITLE
GDAL_DATA and PROJ_LIB not set correctly?

### ISSUE THREAD

**Issue by bu-ra3y** [RemotePixel/amazonlinux-gdal#2]
### Warnings on AWS Lambda
When running on Lambda, I see 2 warnings:
```
[WARNING]	2018-05-25T15:44:39.443Z	88a...	GDAL data files not located, GDAL_DATA not set
[WARNING]	2018-05-25T15:44:39.443Z	88a...	PROJ data files not located, PROJ_LIB not set
```

When I look at your Docker image, I find this:
```
bash-4.2# $GDAL_DATA
bash: /tmp/app/local/lib/gdal: No such file or directory
bash-4.2# $PROJ_LIB
bash-4.2# 
```
`$GDAL_DATA` wasn't pointing to a folder that exists. 

### Solution on the Docker image
I can find a file that I think `$GDAL_DATA` needs to point to (or at least it's parent directory):
```
bash-4.2# find / -name gcs.csv
/tmp/app/local/share/gdal/gcs.csv
```
So maybe 
 - `$GDAL_DATA` should point to: `/tmp/app/local/share/gdal/`
 - `$PROJ_LIB` should point to: `/tmp/app/local/share/proj/`

### Solution for Lambda
Additionally you could add a line to your setup instructions:

> Set these environment variables on AWS Lambda:
> `$GDAL_DATA` to `/var/task/share/gdal/`
> `$PROJ_LIB` to `/var/task/share/proj/`

**Comment by vincentsarago** [comment]
Thanks @bu-ra3y I'll update the docs
