### ISSUE TITLE
gdal / py version matrix additions

### ISSUE THREAD

**Issue by dazza-codes** [RemotePixel/amazonlinux-gdal#20]
Please add
- gdal 2.x with py 3.7
- gdal 3.x with py 3.6

**Comment by vincentsarago** [comment]
dear @darrenleeweber 
This repo is part of a personal project, because it's freely available on Github you can edit/update/push the change you need. 

I'll be happy to review any PR.

thanks

**Comment by dazza-codes** [comment]
PR #21 for example (but the branch structure of the repo is not exactly conducive to this kind of request for more branches with different branch names; makes you wonder about how to create abstractions/scripts for common elements of the builds and how to use parameterized builds)
