### ISSUE TITLE
2.3 Can't get Rasterio working on Lambda using amazonlinux-gdal:2.3.0

### ISSUE THREAD

**Issue by bu-ra3y** [RemotePixel/amazonlinux-gdal#5]
On Lambda, I run into:
```python
Traceback (most recent call last):
  File "/var/task/complete_surveys.py", line 84, in lambda_handler
    import rasterio
  File "/var/task/vendored/rasterio/__init__.py", line 23, in <module>
    from rasterio._base import gdal_version
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /var/task/lib/libgdal.so)
```

It works if I switch to the amazonlinux-gdal:2.2.2 image. 

I think the error means that the problem is something like: gdal was built against a different version of gcc than what is on the Lambda environment. 

I wonder if the issue stems from where you start your image:
```Dockerfile
FROM amazonlinux:latest
```
Which means amazonlinux:2.0.20180622.1 ([amazonlinux tags](https://hub.docker.com/_/amazonlinux/)), which is pretty new.

But, Amazon seems to say that Lambda runs on an older-sounding AMI amzn-ami-hvm-2017.03.1.20170812-x86_64-gp2 ([link](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)).

**Comment by vincentsarago** [comment]
:-( you are right I think
for gdal2.3 we use the latest gcc release because it's not compatible with the old version shipped by default in amazonlinux. 

This is a `won't fix` issue sadly, I'm going to update the readme and point to `amazonlinux-gdal:2.2.2 ` for lambda deploy.

Thanks a lot for reporting the issue @bu-ra3y

**Comment by vincentsarago** [comment]
dear @bu-ra3y this issue should be fixed by now, I've push two new images on docker hub (2.3.0 and 2.3.1) that should work fine on aws lambda. 

Thanks again for opening the issue 🙏

**Comment by bu-ra3y** [comment]
I'll check it out when I get time / need.
