### ISSUE TITLE
I am confused about the branch and tag names vs gdal version

### ISSUE THREAD

**Issue by bu-ra3y** [RemotePixel/amazonlinux-gdal#6]
Hi! Thanks for your work! I depend on it. 

My problem is that I can't say which GDAL version is used in each Docker Image tag. I think that the tag name indicates the GDAL version but that is not exactly backed up by your README.

## Details
The README mentions two GDAL versions (https://github.com/RemotePixel/amazonlinux-gdal#gdal-versions): `master` and `2.4.0`

Later (https://github.com/RemotePixel/amazonlinux-gdal/tree/gdalmaster#version) under Version the README states that GDAL `2.4.0` is used regardless of the branch. 

At Docker Hub (https://hub.docker.com/r/remotepixel/amazonlinux-gdal/tags), there are 3 tags available: 
`2.3.2`
`2.4.0`
`master`

## Suggestion
- In your README I would state the relationship between branch names and GDAL versions more explicitly, something like this:
> ## GDAL Versions
> The branch name tells you which GDAL version is used:
> - master: (GDAL commit 9598f77e1 - 18 Jan 2019)
> - gdal2.4.0: GDAL 2.4.0
- If it is true that the Docker Image tag indicates the GDAL version, then I recommend that you state that clearly on Docker Hub. Because you use your GitHub Readme on Docker Hub you could ammend your Readme with something like:
> ## Docker Images on Docker Hub
> The tag indicates which version of GDAL is packaged with the image, just like the branch names in this repository. There may be more tags hosted on Docker Hub than there are branches in this repository, which just indicates that the images is an older one that I no longer maintain a branch for.

**Comment by vincentsarago** [comment]
👋 @bu-ra3y 
Alrigh I started to think about the re-organisation in #9, here is what I think I'm going to do.

Github:
- master branch: general information about the repo, how to create lambda function... 
- gdal2.4.0 branch: docker file for gdal 2.4.0
- gdal2.3.2 branch: docker file for gdal 2.3.2
- gdalmaster branch: docker file for gdal HEAD 

In the future I'll try to focus only on GDAL update to create new tags/branch and not change the images already in place.

**Comment by bu-ra3y** [comment]
@vincentsarago , no comment , go for it, I love your work.

**Comment by vincentsarago** [comment]
I've changed a bit but I hope it will make it clearer. 
We now have a `master` branch with only repo/docker hub information and 6 other branches
- gdal2.5.0dev
- gdal2.5.0dev-light
- gdal2.4.0
- gdal2.4.0-light
- gdal2.3.2
- gdal2.3.2-light

I've updated the readme on docker hub too
