### ISSUE TITLE
switch over to lambci docker image

### ISSUE THREAD

**Issue by vincentsarago** [RemotePixel/amazonlinux-gdal#8]
👀 https://github.com/lambci/docker-lambda

**Comment by bu-ra3y** [comment]
@vincentsarago , if you head down this path, I would be interested in your experience, good and bad with lambci.

**Comment by vincentsarago** [comment]
@bu-ra3y I did switch over https://github.com/RemotePixel/amazonlinux-gdal/pull/9/files#diff-3254677a7917c6c01f55212f86c57fbfR1

and for now I find it easier. I think the old image I was using wasn't updated so lambci is definitely a better way

**Comment by bu-ra3y** [comment]
Ok, great 👏

**Comment by vincentsarago** [comment]
done in #9
